".zsh/zsh-autosuggestions":
  type: "git-repo"
  url: "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod: "168h"

".zsh/fast-syntax-highlighting":
  type: "git-repo"
  url: "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
  refreshPeriod: "168h"

".config/nvim":
  type: "git-repo"
  url: "https://github.com/AstroNvim/AstroNvim.git"
  refreshPeriod: "168h"

".tmux/plugins/tpm":
  type: "git-repo"
  url: "https://github.com/tmux-plugins/tpm.git"
  refreshPeriod: "168h"

# Ranger plugins

".config/ranger/plugins/devicons2":
  type: "git-repo"
  url: "https://github.com/cdump/ranger-devicons2.git"
  refreshPeriod: "168h"

".config/ranger/plugins/archives":
  type: "git-repo"
  url: "https://github.com/maximtrp/ranger-archives.git"
  refreshPeriod: "168h"

".config/ranger/plugins/fzf-filter":
  type: "git-repo"
  url: "https://github.com/MuXiu1997/ranger-fzf-filter.git"
  refreshPeriod: "168h"
